swagger: '2.0'

info:
  version: "1.0.0"
  title: keiba_api

paths:
  /v1/races:
    get:
      description: |
        レース一覧を取得する.
      parameters:
        -
          name: date
          in: query
          description: レース一覧を取得する日付
          required: true
          type: string
          format: date
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            title: ArrayOfRaces
            type: array
            items:
              $ref: "#/definitions/Race"
  /v1/races/{raceid}/detail:
    get:
      description: レース詳細を取得する.
      responses:
        200:
          description: Successful response
          schema:
            title: RaceDetail
            $ref: "#/definitions/RaceDetail"
definitions:
  Race:
    type: object
    properties:
      id:
        type: string
        example: "2019122210611"
      courseid:
        type: string
        example: "106"
      coursename:
        type: string
        example: "中山"
      racenumber:
        type: integer
        format: int32
        example: 11
      racename:
        type: string
        example: 有馬記念
    required:
      - id
      - courseid
      - coursename
      - racenumber
      - racename
  RaceDetail:
    type: object
    properties:
      raceinfo:
        $ref: "#/definitions/Race"
      horses:
        type: array
        items:
          $ref: "#/definitions/HorseInRace"
  HorseInRace:
    type: object
    properties:
      bracketnumber:
        type: integer
        example: 3
      horsenumber:
        type: integer
        example: 6
      horseid:
        type: string
        example: 0001191589
      horsename:
        type: string
        example: リスグラシュー
    required:
      - horsename
