/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/races": {
    /** レース一覧を取得する. */
    get: {
      parameters: {
        query: {
          /** レース一覧を取得する日付 */
          date: string;
        };
      };
      responses: {
        /** Successful response */
        200: {
          schema: definitions["Race"][];
        };
      };
    };
  };
  "/v1/races/{raceid}/detail": {
    /** レース詳細を取得する. */
    get: {
      responses: {
        /** Successful response */
        200: {
          schema: definitions["RaceDetail"];
        };
      };
    };
  };
}

export interface definitions {
  Race: {
    /** @example 2019122210611 */
    id: string;
    /** @example 106 */
    courseid: string;
    /** @example 中山 */
    coursename: string;
    /**
     * Format: int32
     * @example 11
     */
    racenumber: number;
    /** @example 有馬記念 */
    racename: string;
  };
  RaceDetail: {
    raceinfo?: definitions["Race"];
    horses?: definitions["HorseInRace"][];
  };
  HorseInRace: {
    /** @example 3 */
    bracketnumber?: number;
    /** @example 6 */
    horsenumber?: number;
    /** @example 1191589 */
    horseid?: string;
    /** @example リスグラシュー */
    horsename: string;
  };
}

export interface operations {}

export interface external {}
