name: build-and-deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: KeibaApi
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Copy testdata
        run: |
          aws s3 sync ${{ secrets.UNITTESTDATA_URI }} testdata
          ls -l testdata
      - name: Test
        run: yarn test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Install sam-cli
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.67.0
      - name: Build
        run: yarn build
      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/master')
        run: sam deploy --stack-name KeibaApiProd --s3-bucket ${{ secrets.AWS_SAM_BUCKET_NAME }} --s3-prefix KeibaApiProd --capabilities CAPABILITY_IAM --parameter-overrides "Region=ap-northeast-1 Bucket=masaminh-keiba-cache-bucket DomainName=${{ secrets.DOMAIN_NAME }} HostedZoneId=${{ secrets.HOSTEDZONE }}" --no-fail-on-empty-changeset
